### PR TITLE
Add support for custom error types in `der`.

### PR DESCRIPTION
**Pull request by turbocool3r**
See https://github.com/RustCrypto/formats/pull/1055 for more info.

### CODE REVIEW

**Comment by turbocool3r** [comment]
Should I update the links to point to the upstream repo since https://github.com/RustCrypto/formats/pull/1055 is merged?

**Comment by tarcieri** [comment]
Yes please. Thanks! Then we can merge this.

**Comment by turbocool3r** [comment]
It seems the checks pass

**Comment by tarcieri** [comment]
Thanks!

**Pull request merged**
